pentaho/pdi-dataservice-server-plugin

- src/main/java/org/pentaho/di/trans/dataservice/SqlTransGenerator.java
- src/test/java/org/pentaho/di/trans/dataservice/SqlTransGeneratorTest.java
Group By and aggregate functions.
Formerly the Select values step in the generated transformation was
omitted if aggregates were present in the select field.  This was
assumed to be valid since fields and aggregate alias could be handled
in the Group By, but failed to handle cases where the aggregate field
was to the left of any of the GROUP BY columns.  Also failed to handle
aliases for the GROUP BY columns.
@hudak @bmorrise
> [BACKLOG-5268] Alias and column order can be incorrect when using

- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceTestDialog.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogController.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/menu/DataServiceStepHandler.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogControllerTest.java
Since dialogs are not reused, dispose resources instead of hiding them on close
Also ensure each dialog gets its own SWT Shell
http://jira.pentaho.com/browse/BACKLOG-5218
> [BACKLOG-5218]Dispose dialogs

- src/test/java/org/pentaho/di/trans/dataservice/DataServiceContextTest.java
Missed license header in #117 
[![Build Status](https://travis-ci.org/hudak/pdi-dataservice-server-plugin.svg?branch=licenses)](https://travis-ci.org/hudak/pdi-dataservice-server-plugin)
> [CLEANUP]License headers

- src/main/java/org/pentaho/di/trans/dataservice/optimization/paramgen/AutoParameterGenerationService.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/paramgen/AutoParameterGenerationServiceTest.java
Columns are switched when running 'Get Optimizations', should be reversed
Only relevant when Data Service field and Step Field are different
> [BACKLOG-5220]Swap 'Data Service'/Step Fields

- src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedService.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedServiceTest.java
Only use cache for answering a 'SELECT DISTINCT ...' query when a complete result set is available
http://jira.pentaho.com/browse/BACKLOG-5460
[![Build Status](https://travis-ci.org/hudak/pdi-dataservice-server-plugin.svg?branch=BACKLOG-5460)](https://travis-ci.org/hudak/pdi-dataservice-server-plugin)
> [BACKLOG-5460]DISTINCT requires complete cache

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
Logical error writes rowMeta after data is complete.
Should write meta only once, either before the first row or after the trans has finished if empty
[![Build Status](https://travis-ci.org/hudak/pdi-dataservice-server-plugin.svg?branch=master)](https://travis-ci.org/hudak/pdi-dataservice-server-plugin)
http://jira.pentaho.com/browse/BACKLOG-5818
> [BACKLOG-8518]Executor should write RowMeta once

- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogController.java
- src/main/resources/org/pentaho/di/trans/dataservice/ui/messages/messages_en_US.properties
Changed error message on empty DS name according to UX review.
@hudak please review. Should Test button be disabled if name is empty?
> [BACKLOG-4455] In Data Service Test dialog, current data service must be specified

- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestControllerTest.java
in the default SQL.
This prevents errors/ambiguity if there are spaces within the name.
> [BACKLOG-6650] Test dataservice dialog should quote the tablename

- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestControllerTest.java
Tests require a timeout() during verification to
wait for spawned thread completion.  Originally
set to wait 500 ms, which is occasionally insufficient.
> [TEST] Addressing 3 sporadically failing tests

- src/main/java/org/pentaho/di/trans/dataservice/SqlTransGenerator.java
Changes to SelectValuesMeta prevent direct modification
of the arrays which back the SelectName and SelectRename
properties.
We shouldn't be using a getter as a covert setter.
> [TEST]  Fixing test failure in SqlTransGeneratorTest

- src/main/java/org/pentaho/di/trans/dataservice/SqlTransGenerator.java
- Changes to SelectValuesMeta prevent direct modification of the arrays which back the SelectName and SelectRename properties. (cherry pick of https://github.com/pentaho/pdi-dataservice-server-plugin/pull/163)
- Checkstyle applied
We need this because later SelectValuesMeta was returning [reference to it's array] (https://github.com/pentaho/pentaho-kettle/commit/a4642ea524f2f47307570b40422393f7c13f6b9e#diff-1182c336cfd9a2b957cad23ea11106b1L142), but now it returnes [it's copy] (https://github.com/pentaho/pentaho-kettle/blob/6.1/engine/src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMeta.java#L125).
@mchen-len-son, @pamval  could you please review this PR?
> [SP-2706] Backport of PDI-15032 - Metadata Injection on all tabs of select values step is causing error (6.1 Suite)

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceContext.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
- src/main/resources/OSGI-INF/blueprint/services.xml
- src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactoryTest.java
* Replaced concurrent map in context with in-memory cache to prevent leaks
* Replaced Byte Array streams with pipe to improve performance and memory footprint
http://jira.pentaho.com/browse/BACKLOG-11615
@pamval @mkambol
> [BACKLOG-11615]Fix Dataservice Mem problems

- src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceObserver.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceObserverTest.java
The row data (Object[]) passed via a rowWrittenEvent is mutable
and may be modified by subsequent steps, potentially resulting in
datatype errors.  Adding a defensive copy of the row to assure
consistency when the object is retrieved from cache.
http://jira.pentaho.com/browse/BACKLOG-11690
Pull request to master: https://github.com/pentaho/pdi-dataservice-server-plugin/pull/218
@kcruzada @dkincade
> [BACKLOG-11690] Mutable cached data causes incorrect results

- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
[SP-3229][PDI-15584] It's possible to create data services with duplicate names via Save AS button for transformations
-added consistent behavior with YES button (affected when transformation and press Save as)
@kurtwalker Could you please review and merge it?
> [SP-3229][PDI-15584] It's possible to create data services with duplicate names via Save AS button for transformations

- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
[SP-3228][PDI-15584] It's possible to create data services with duplicate names via Save AS button for transformations
-added consistent behavior with YES button (affected when transformation and press Save as)
@kurtwalker Could you please review and merge it?
> [SP-3228][PDI-15584] It's possible to create data services with duplicate names via Save AS button for transformations

- src/main/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolver.java
@ddiroma @mdamour1976 The transmeta gets cloned further down in the data service executor, but the annotations query didn't.
> [BACKLOG-16227] Clone transient data service transmeta

- impl/src/main/java/org/pentaho/di/trans/dataservice/resolvers/DataServiceResolverDelegate.java
Short-circuiting was preventing `ThinDatabaseMetaData.getServices` to find transient data services (because it was the second resolver... the same could happen for "normal" metastore data services if it was the first resolver), and so `ThinDatabaseMetaData.getColumns` would always return an empty ResultSet in such cases.
@pentaho/millenniumfalcon please review.
> [BACKLOG-25511] Return data services' names from all providers

- impl/pom.xml
javax.annotation aka findbugs annotations from two different dependency chains in karaf; one from guava and one that it declared itself (using an older version).  Suppressing the self-declared dependency and allowing guava to pull in its version seems to have solved the problem.
> [BACKLOG-38063] pdi-dataservice-server-plugin bundle was getting the

- impl/src/main/java/org/pentaho/di/trans/dataservice/serialization/TransImportExtensionPointPlugin.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/ui/DriverDetailsDialog.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/www/BaseServletTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/www/ListDataServicesServletTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/www/TransDataServletTest.java
- pom.xml
[BACKLOG-42752]-Upgrading pdi-dataservice-server-plugin from Java EE to Jakarta-EE
[BACKLOG-42752]: https://hv-eng.atlassian.net/browse/BACKLOG-42752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-42752]-Upgrading pdi-dataservice-server-plugin from Java EE to Jakarta-EE

- impl/src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
[BACKLOG-43935]-Fix JDK21 test pipeline(test1) test case failures
[BACKLOG-43935]: https://hv-eng.atlassian.net/browse/BACKLOG-43935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43935]-Fix JDK21 test pipeline(test1) test case failures

- impl/src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceRemapNoStepsDialogControllerTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/www/BaseServletTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/www/ListDataServicesServletTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/www/TransDataServletTest.java
This pull request includes updates to test files in the `impl/src/test/java/org/pentaho/di/trans/dataservice` directory to address race conditions in multithreaded tests, ensure compatibility with the `jakarta.servlet` package, and improve assertions in controller tests.
* Added `Thread.sleep(2000)` in multiple test methods (`testWriteFailure`, `testWindowQueryWriteFailure`, `testInputStreamClosed`, `testWindowInputStreamClosed`) to prevent race conditions between the main thread and executor service threads. Updated `logError` verification to use `isNull()` for null argument matching. (`[[1]](diffhunk://#diff-9890648be827cb7ba56eb583629b3f3b960934329cb44a15aa160001134692d3L185-R188)`, `[[2]](diffhunk://#diff-9890648be827cb7ba56eb583629b3f3b960934329cb44a15aa160001134692d3L201-R206)`, …
> [BACKLOG-40823] - Upgrade the Tomcat version from current to 10.x.x with Java 17  
