- src/main/java/org/pentaho/di/trans/dataservice/serialization/ServiceTrans.java
> [BACKLOG-5174]Null check file location

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
- src/main/java/org/pentaho/di/trans/dataservice/www/TransDataServlet.java
> [BACKLOG-5183] Fix dual table support in data services

- src/main/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationService.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/TransOpenedExtensionPointPlugin.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogController.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationServiceTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/TransOpenedExtensionPointPluginTest.java
Ensure that there is always a synchronization service installed after saving a Data Service
Dependant on pentaho/pentaho-kettle#1771
@mkambol
> [BACKLOG-3431]Register SynchronizationService on DataService edit

- src/main/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationService.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationServiceTest.java
> [BACKLOG-3431]Show sync errors on display thread

- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtilTest.java
> [BACKLOG-4184]Fail conflict check only if reference exists

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
> [BACKLOG-5340] Fixed issue with long sql queries in GET request

- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestControllerTest.java
Also addresses BACKLOG-5342
@bmorrise @mkambol 
FYI @dkincade @kcruzada
> [BACKLOG-5366]Defer executor until test execute/preview

- src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedServiceLoader.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedServiceTest.java
@hudak 
Test Results:
Tests run: 166, Failures: 0, Errors: 0, Skipped: 0
> [BACKLOG-5540] Fixed db connection issue with cached data services

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceContext.java
- src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/ServiceTrans.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogController.java
- src/main/resources/org/pentaho/di/trans/dataservice/messages/messages_en_US.properties
- src/main/resources/org/pentaho/di/trans/dataservice/ui/messages/messages_en_US.properties
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedServiceTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCacheTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogControllerTest.java
+ Check for empty DS name before test dialog appears
+ Check if table name in sql has same name as the DS being tested
@hudak
> [BACKLOG-4455] In Data Service Test dialog, current data service must be specified

- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceTestDialog.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogController.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/menu/DataServiceStepHandler.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogControllerTest.java
Since dialogs are not reused, dispose resources instead of hiding them on close
Also ensure each dialog gets its own SWT Shell
> [SP-2177][BACKLOG-5218]Dispose dialogs

- pom.xml
Add dependency info for servlet and UI libraries
> [CLEANUP]Add transitive dependencies

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceContext.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceValidationException.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationService.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/TransOpenedExtensionPointPlugin.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogController.java
- src/test/java/org/pentaho/di/trans/dataservice/BaseTest.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceContextTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtilTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationServiceTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/TransOpenedExtensionPointPluginTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogControllerTest.java
[![Build Status](https://travis-ci.org/hudak/pdi-dataservice-server-plugin.svg?branch=master)](https://travis-ci.org/hudak/pdi-dataservice-server-plugin)
> Additional Testing

- src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
- src/test/java/org/pentaho/di/trans/dataservice/BaseTest.java
- src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtilTest.java
- src/test/java/org/pentaho/di/trans/dataservice/testing/answers/ReturnsSelf.java
- src/test/java/org/pentaho/di/trans/dataservice/www/ListDataServicesServletTest.java
- src/test/java/org/pentaho/di/trans/dataservice/www/TransDataServletTest.java
[![Build Status](https://travis-ci.org/hudak/pdi-dataservice-server-plugin.svg?branch=master)](https://travis-ci.org/hudak/pdi-dataservice-server-plugin)
> More Testing

- src/main/java/org/pentaho/di/trans/dataservice/optimization/paramgen/ui/ParameterGenerationController.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/paramgen/ui/ParameterGenerationControllerTest.java
http://jira.pentaho.com/browse/BACKLOG-4004
[![Build Status](https://travis-ci.org/bmorrise/pdi-dataservice-server-plugin.svg?branch=BACKLOG-4004)](https://travis-ci.org/bmorrise/pdi-dataservice-server-plugin)
http://10.100.11.222:8080/job/wingman-mvn/57/
> [BACKLOG-4004] Fix for data service opt dialog delete/edit buttons

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceContext.java
- src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactory.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
- src/main/java/org/pentaho/di/trans/dataservice/www/ListDataServicesServlet.java
- src/main/java/org/pentaho/di/trans/dataservice/www/ServletRepositoryAdapter.java
- src/main/java/org/pentaho/di/trans/dataservice/www/TransDataServlet.java
- src/main/resources/OSGI-INF/blueprint/services.xml
- src/main/resources/org/pentaho/di/trans/dataservice/serialization/messages/messages_en_US.properties
- src/test/java/org/pentaho/di/trans/dataservice/BaseTest.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceContextTest.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
- src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactoryTest.java
- src/test/java/org/pentaho/di/trans/dataservice/www/BaseServletTest.java
- src/test/java/org/pentaho/di/trans/dataservice/www/ListDataServicesServletTest.java
- src/test/java/org/pentaho/di/trans/dataservice/www/TransDataServletTest.java
Bind client to a repository supplier, eliminating the need to set repository and metastore.
Local data service client will use Spoon's current repository, or the user's local metastore if not connected.
http://jira.pentaho.com/browse/PDI-14537
> [PDI-14537] Fix Local Data Service client

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCache.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
http://jira.pentaho.com/browse/PDI-14551
[![Build Status](https://travis-ci.org/bmorrise/pdi-dataservice-server-plugin.svg?branch=PDI-14551-2)](https://travis-ci.org/bmorrise/pdi-dataservice-server-plugin)
> [PDI-14551] Fix for caching stopped data service

- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DriverDetailsDialog.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/UIFactory.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DriverDetailsDialogController.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DriverDetailsDialogTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogControllerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DriverDetailsDialogControllerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/menu/DataServiceStepHandlerTest.java
> [BACKLOG-5020] Tests

- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogController.java
[![Build Status](https://travis-ci.org/bmorrise/pdi-dataservice-server-plugin.svg?branch=CLEANUP)](https://travis-ci.org/bmorrise/pdi-dataservice-server-plugin)
> [CLEANUP] Restoring access modifiers

- src/main/java/org/pentaho/di/trans/dataservice/optimization/paramgen/ui/ParameterGenerationModel.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ParameterPushdown.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ParameterPushdownFactory.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ui/ParameterPushdownController.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ui/ParameterPushdownModel.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/AbstractModel.java
- src/main/resources/OSGI-INF/blueprint/services.xml
- src/main/resources/org/pentaho/di/trans/dataservice/optimization/paramgen/ui/param-gen-overlay.xul
- src/main/resources/org/pentaho/di/trans/dataservice/optimization/pushdown/ui/overlay.xul
- src/test/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ParameterPushdownFactoryTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ParameterPushdownTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ui/ParameterPushdownControllerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ui/ParameterPushdownModelTest.java
[![Build Status](https://travis-ci.org/hudak/pdi-dataservice-server-plugin.svg?branch=BACKLOG-4899)](https://travis-ci.org/hudak/pdi-dataservice-server-plugin)
http://jira.pentaho.com/browse/BACKLOG-4899
> [BACKLOG-4899] Parameter Pushdown UI

- src/main/java/org/pentaho/di/trans/dataservice/CommandExecutor.java
- src/main/java/org/pentaho/di/trans/dataservice/DataServiceContext.java
- src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/CommandQueryService.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/DualQueryService.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/ExecutorQueryService.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/Query.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCache.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactory.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceTestDialog.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/UIFactory.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
- src/main/java/org/pentaho/di/trans/dataservice/www/TransDataServlet.java
- src/test/java/org/pentaho/di/trans/dataservice/CommandExecutorTest.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
- src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedServiceTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCacheTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactoryTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestControllerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/www/TransDataServletTest.java
http://jira.pentaho.com/browse/BACKLOG-3195
[![Build Status](https://travis-ci.org/bmorrise/pdi-dataservice-server-plugin.svg?branch=BACKLOG-3195)](https://travis-ci.org/bmorrise/pdi-dataservice-server-plugin)
> [BACKLOG-3195] Added invalid cache for stop and fail

- src/main/resources/org/pentaho/di/trans/dataservice/optimization/pushdown/ui/overlay.xul
pushes a variable into context (UI only)
Updated descriptive text based on Ux feedback
@bmorrise
> [BACKLOG-4899] As an ETL dev, I'd like a new push down type that

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- src/main/java/org/pentaho/di/trans/dataservice/execution/CopyParameters.java
- src/main/java/org/pentaho/di/trans/dataservice/execution/PrepareExecution.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/PushDownOptimizationMeta.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/StepOptimization.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedService.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCache.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/paramgen/ParameterGeneration.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ParameterPushdown.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/PushDownOptimizationMetaTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/StepOptimizationTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ParameterPushdownTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtilTest.java
[![Build Status](https://travis-ci.org/hudak/pdi-dataservice-server-plugin.svg?branch=BACKLOG-5551)](https://travis-ci.org/hudak/pdi-dataservice-server-plugin)
@mkambol @bmorrise @deinspanjer
> [BACKLOG-5551]ParameterPushdown Optimization

- src/main/java/org/pentaho/di/trans/dataservice/www/TransDataServlet.java
- src/test/java/org/pentaho/di/trans/dataservice/www/TransDataServletTest.java
http://jira.pentaho.com/browse/PDI-12569
> [PDI-12569] Moved sql query to post body

- src/main/java/org/pentaho/di/trans/dataservice/optimization/mongod/MongoFunc.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/mongod/MongodbPredicateTest.java
http://jira.pentaho.com/browse/PDI-14488
> [PDI-14488] Add LIKE comparison capability for mongodb pushdown

- src/main/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ParameterPushdown.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ParameterPushdownFactory.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ui/ParameterPushdownController.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ui/ParameterPushdownModel.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/model/DataServiceModel.java
- src/main/resources/org/pentaho/di/trans/dataservice/optimization/pushdown/ui/overlay.xul
- src/test/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ui/ParameterPushdownModelTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/model/DataServiceModelTest.java
http://jira.pentaho.com/browse/BACKLOG-6117
> [BACKLOG-6117] Add step field list to parameter pushdown

- src/main/resources/org/pentaho/di/trans/dataservice/optimization/pushdown/ui/overlay.xul
> [BACKLOG-5999]  Updating param pushdown columns per Ux.

- src/main/resources/org/pentaho/di/trans/dataservice/ui/xul/dataservice-test-dialog.xul
Remove reference to non existing menu
> [BACKLOG-5880] SWT Error when opening Test Data Service dialog

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- src/main/java/org/pentaho/di/trans/dataservice/SqlTransGenerator.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/ValueMetaResolver.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
- src/test/java/org/pentaho/di/trans/dataservice/SqlTransGeneratorTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedServiceTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCacheTest.java
Inject resolved row meta into sql parser
Set ANSI conversion masks in generated transformation
http://jira.pentaho.com/browse/BACKLOG-5847
> [BACKLOG-5847]Force ANSI SQL types in genTrans

- src/main/resources/org/pentaho/di/trans/dataservice/ui/messages/messages_en_US.properties
> [BACKLOG-6554]  Updating doc links to 6.1.

- src/main/resources/org/pentaho/di/trans/dataservice/ui/messages/messages_en_US.properties
Remove webappname property from URL
@mkambol
> [BACKLOG-5068]Update Driver Details URL

- doc/suggestedCachingServiceChange.md
@hudak Here's the documentation for the Spike, please feel free to review and merge it in for the KT Session.
> [BACKLOG-7488]  Adding documentation for Spike

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceMeta.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceMetaTest.java
DataServiceMeta class.
What was done:
1) added properties
> BACKLOG-8644 - Dev:Define additional metadata for a transient service on

- src/main/java/org/pentaho/di/trans/dataservice/ui/menu/DataServiceStepHandler.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/menu/DataServiceStepHandlerTest.java
transient services.
What was done:
1) changed behavior
2) added unit tests
> BACKLOG-8647 -- Dev: Change Data Service creation to remove existing

- src/main/java/org/pentaho/di/trans/dataservice/SqlTransGenerator.java
- Changes to SelectValuesMeta prevent direct modification of the arrays which back the SelectName and SelectRename properties.
- Checkstyle applied
> [SP-2706] Backport of PDI-15032 - Metadata Injection on all tabs of select values step is causing error (6.1 Suite)

- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
- When creating data service with no service - step specified, take the last step from active transformation and mark it sa service - step
- Tests written
- Checkstyle applied
> [PDI-15153] Creating Data Services via View Panel - New Data ServiceParameter Pushdown - Error with Parameters not showing up

- .gitignore
- pom.xml
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceRemapConfirmationDialog.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceRemapNoStepsDialog.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceRemapStepChooserDialog.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceStepDeleteExtensionPointPlugin.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/UIFactory.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceRemapConfirmationDialogController.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceRemapNoStepsDialogController.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceRemapStepChooserDialogController.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/model/DataServiceRemapStepChooserModel.java
- src/main/resources/OSGI-INF/blueprint/plugins.xml
- src/main/resources/org/pentaho/di/trans/dataservice/ui/messages/messages_en_US.properties
- src/main/resources/org/pentaho/di/trans/dataservice/ui/xul/dataservice-remap-confirmation-dialog.xul
- src/main/resources/org/pentaho/di/trans/dataservice/ui/xul/dataservice-remap-no-steps-dialog.xul
- src/main/resources/org/pentaho/di/trans/dataservice/ui/xul/dataservice-remap-step-chooser-dialog.xul
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceRemapConfirmationDialogTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceRemapNoStepsDialogTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceRemapStepChooserDialogTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceStepDeleteExtensionPointPluginTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceRemapConfirmationDialogControllerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceRemapNoStepsDialogControllerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceRemapStepChooserDialogControllerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/model/DataServiceRemapStepChooserModelTest.java
@hudak @mkambol
Kettle part: https://github.com/pentaho/pentaho-kettle/pull/2658
> [BACKLOG-7526] Removing a step with a data service should allow remapping or deleting the service

- doc/suggestedCachingServiceChange.md
@hudak Just added some more documentation.
> [BACKLOG-7488]  Adding additional option for Spike documentation

- src/main/java/org/pentaho/di/trans/dataservice/clients/AnnotationsQueryService.java
Improve the AnnotationsQueryService to gather annotations without executing the transformation
> [BACKLOG-10033] Improve the AnnotationsQueryService 

- src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
- src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
PR https://github.com/pentaho/pdi-dataservice-plugin/pull/69 must be committed first before this one.
> [BACKLOG-10111] Add api methods for querying specific services

- src/main/java/org/pentaho/di/trans/dataservice/clients/AnnotationsQueryService.java
- src/test/java/org/pentaho/di/trans/dataservice/clients/AnnotationsQueryServiceTest.java
> [BACKLOG-10272] get only upstream annotations

- pom.xml
- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaObjectFactory.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceReferenceSynchronizer.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/EmbeddedMetaStoreFactory.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationListener.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/TransOpenedExtensionPointPlugin.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaObjectFactoryTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceReferenceSynchronizerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationListenerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/TransOpenedExtensionPointPluginTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogControllerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceRemapStepChooserDialogControllerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestControllerTest.java
Refactor of DataServiceMetaStoreUtil to extract out .sync()
functionality into a single purpose class.
http://jira.pentaho.com/browse/BACKLOG-3736
> [BACKLOG-3736]  Data Services should work after importing.

- src/main/java/org/pentaho/di/trans/dataservice/serialization/TransImportExtensionPointPlugin.java
- src/main/resources/org/pentaho/di/trans/dataservice/serialization/messages/messages_en_US.properties
- src/test/java/org/pentaho/di/trans/dataservice/serialization/TransImportExtensionPointPluginTest.java
Change logging level, fix message param
@mkambol
> [BACKLOG-4365] Dev- add kettle extension points to appropriate places

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- src/main/java/org/pentaho/di/trans/dataservice/SqlTransGenerator.java
- src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedService.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
- src/test/java/org/pentaho/di/trans/dataservice/SqlTransGeneratorTest.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedServiceTest.java
@mdamour1976 @bmorrise please review
> [BACKLOG-10322] service transformation limit for non user defined dataservices

- src/main/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolver.java
- src/test/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolverTest.java
> [BACKLOG-10322] have transient dataservices marked as not user defined

- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
- src/main/java/org/pentaho/di/trans/dataservice/serialization/ServiceTrans.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceReferenceSynchronizerTest.java
- src/test/java/org/pentaho/di/trans/dataservice/serialization/ServiceTransTest.java
> [BACKLOG-10941] NPE in pentaho.log when deleting any imported data services from PUC & emptying the Trash

- src/main/java/org/pentaho/di/trans/dataservice/clients/AnnotationsQueryService.java
contains annotations in metastore
What was done:
1) added fallback for metastore
> BACKLOG-11220 - DET - exception occur opening DET when Annotate Stream

- src/main/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolver.java
- src/test/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolverTest.java
The transformation in the transient request may be from the local filesystem, even after connecting to the repository.
This change always falls back to the local filesystem if loading from the repository fails.
@bmorrise
> [BACKLOG-115159]TransientResolver tires local if repo fails

- src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
- src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
If the client DataInputStream is closed before the query is completely written, an IOExcepiton may be logged. This change makes the write end defensive.
If the input stream is closed, the output stream will remain open. More data may be written to the output stream, but it will be ignored.
@bmorrise / @mkambol / @mdamour1976 Please review, thank you!
> [BACKLOG-11677]Write query results to safe pipe

- src/main/java/org/pentaho/di/trans/dataservice/optimization/paramgen/MongodbInputParameterGeneration.java
@mbatchelor, @mkambol, could you please take a look?
> [PPP-3506] - XXE Security Vulnerability in xml parsers

- src/main/java/org/pentaho/di/trans/dataservice/SqlTransGenerator.java
- src/test/java/org/pentaho/di/trans/dataservice/SqlTransGeneratorTest.java
For TYPE_INTEGER fields, the avg calculation will truncate any
decimals.  Most databases will implicitly convert to double in such
cases.  This change alters the type of integer fields used in an
avg aggregation to TYPE_NUMBER prior to the in-memory group by.
http://jira.pentaho.com/browse/BACKLOG-11838
> [BACKLOG-11838] Data Service AVG() aggregates are rounded down

- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
[PDI-15584] It's possible to create data services with duplicate name s via Save AS button for transformations
-remove dataService if user pressed NO in dialog
> [PDI-15584] It's possible to create data services with duplicate name s via Save AS button for transformations

- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
[SP-3228][PDI-15584] It's possible to create data services with duplicate names via Save AS button for transformations
-remove dataService if user pressed NO in dialog
> [SP-3228][PDI-15584] It's possible to create data services with duplicate names via Save AS button for transformations

- src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceMetaStoreUtil.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegateTest.java
[SP-3229][PDI-15584] It's possible to create data services with duplicate names via Save AS button for transformations
-remove dataService if user pressed NO in dialog
> [SP-3229][PDI-15584] It's possible to create data services with duplicate names via Save AS button for transformations

- src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
[PDI-15584] It's possible to create data services with duplicate names via Save AS button for transformations
-added consistent behavior with YES button (affected when transformation and press Save as)
> [PDI-15584] It's possible to create data services with duplicate names via Save AS button for transformations

- src/main/resources/org/pentaho/di/trans/dataservice/ui/messages/messages_en_US.properties
> [BACKLOG-14691] Update data service dialog help url

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/DataServiceClient.java
- src/main/java/org/pentaho/di/trans/dataservice/resolvers/DataServiceResolverDelegate.java
- src/main/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolver.java
- src/main/resources/OSGI-INF/blueprint/services.xml
- src/test/java/org/pentaho/di/trans/dataservice/resolvers/DataServiceResolverDelegateTest.java
Should be merged first: https://github.com/pentaho/pentaho-kettle/pull/3819
Master PR: https://github.com/pentaho/pdi-dataservice-server-plugin/pull/248
7.1.0.0 PR: https://github.com/pentaho/pdi-dataservice-server-plugin/pull/250
> [BACKLOG-15784] Increase performance of transient data services

- src/main/java/org/pentaho/di/trans/dataservice/DataServiceMetaFactory.java
- src/main/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolver.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceMetaFactoryTest.java
- src/test/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolverTest.java
Master PR: https://github.com/pentaho/pdi-dataservice-server-plugin/pull/252
7.1.0.0 PR: https://github.com/pentaho/pdi-dataservice-server-plugin/pull/254
> [BACKLOG-16236] Use active transmeta when trans in spoon

- src/main/java/org/pentaho/di/trans/dataservice/clients/AnnotationsQueryService.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/ExecutorQueryService.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
Reverts pentaho/pdi-dataservice-server-plugin#256
> Revert "[BACKLOG-17014]  Provide key driven Mulit-provider MetastoreLocator"

- src/main/java/org/pentaho/di/trans/dataservice/clients/AnnotationsQueryService.java
- src/main/java/org/pentaho/di/trans/dataservice/clients/ExecutorQueryService.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
Reverts pentaho/pdi-dataservice-server-plugin#259
> Revert "Revert "[BACKLOG-17014]  Provide key driven Mulit-provider MetastoreLocator""

- src/main/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolver.java
- src/test/java/org/pentaho/di/trans/dataservice/DataServiceMetaTest.java
- src/test/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolverTest.java
- src/test/java/org/pentaho/di/trans/dataservice/www/ListDataServicesServletTest.java
@pentaho/millenniumfalcon 
@pentaho/ackbar 
@kurtwalker 
Please Review
> [BACKLOG-17190] Fixed loading a TransMeta from the repository being tied to File.separator which did not work on Windows OS

- pom.xml
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceDialogController.java
- src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DriverDetailsDialogController.java
- src/main/resources-filtered/org/pentaho/di/trans/dataservice/ui/messages/messages_en_US.properties
- src/main/resources/org/pentaho/di/trans/dataservice/ui/messages/messages_en_US.properties
@pentaho/2-1b @pentaho/millenniumfalcon please review
>  [BACKLOG-19262] Update In-Product Links to Documentation

- src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedService.java
- src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedServiceTest.java
- replaced version calculation for the cache key creation
> [BACKLOG-20407] - Replace cache version creation

- assemblies/dataservice-legacy/pom.xml
- pom.xml
> [BACKLOG-21193] Add legacy plugin feature reactivex dependency

- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/streaming/execution/StreamingServiceTransExecutor.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/ui/model/DataServiceModel.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/ui/model/DataServiceModelTest.java
@pentaho/kashyyyk Please review.
> [BACKLOG-21653] - Fix fallback limits.

- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceMeta.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceMetaFactory.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDialog.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/ui/model/DataServiceModel.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/DataServiceMetaFactoryTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/DataServiceMetaTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolverTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/ui/model/DataServiceModelTest.java
@pentaho/kashyyyk Please review
> [BACKLOG-21653] - Unable to save dataservice fix.

- impl/src/main/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactory.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/streaming/execution/StreamingServiceTransExecutor.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactoryTest.java
@pentaho/kashyyyk Please review.
> [BACKLOG-21653] - FIX time limit not being set in data service factory.

- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceMeta.java
@pentaho/kashyyyk Please review
> [BACKLOG-21653] - FIX default streaming value.

- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceContext.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/streaming/execution/StreamingServiceTransExecutor.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceStepDeleteExtensionPointPlugin.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/utils/DataServiceConstants.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/DataServiceContextTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/DataServiceExecutorTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/streaming/execution/StreamingServiceTransExecutorTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/ui/DataServiceStepDeleteExtensionPointPluginTest.java
@pentaho/kashyyyk Please review
> [BACKLOG-22231] - Streaming service transformation restart bug fix.

- impl/src/main/java/org/pentaho/di/trans/dataservice/streaming/StreamServiceKey.java
> [PDI-17344] - Null filter for field without Null values does not work

- assemblies/dataservice/src/main/feature/feature.xml
@pentaho/millenniumfalcon please review
> [BACKLOG-25261] - Providing missing fasterxml annotations.

- assemblies/dataservice/pom.xml
- assemblies/dataservice/src/main/feature/feature.xml
@pentaho/millenniumfalcon please review
Merge together with : https://github.com/pentaho/pentaho-platform-plugin-geo/pull/268
> [BACKLOG-25261] - Providing missing modeler dep.

- impl/src/main/resources/org/pentaho/di/trans/dataservice/ui/messages/messages_en_US.properties
> [BACKLOG-26379] PDI - Data services help link

- impl/src/main/resources/org/pentaho/di/trans/dataservice/ui/messages/messages_en_US.properties
@kcruzada @pvale @jlien @pentaho-svigneri
Master PR: https://github.com/pentaho/pdi-dataservice-server-plugin/pull/357
> [BACKLOG-26379] PDI - Data services help link (#357)

- impl/pom.xml
> [BACKLOG-27567] Added missing OSGi core dependency

- impl/src/main/resources/org/pentaho/di/trans/dataservice/ui/messages/messages_en_US.properties
> [BACKLOG-29422] more updated doc links for 8.3

- impl/pom.xml
- impl/src/test/java/org/pentaho/di/trans/dataservice/execution/DataServiceRealTest.java
> [TEST] The Delay step was extracted from kettle engine, so was no

- impl/pom.xml
- pom.xml
Update to dependencies to handle moving of constant step from engine to plugins/core
> [BACKLOG-22188] Decouple constant step from Kettle engine

- impl/pom.xml
- pom.xml
Reverts pentaho/pdi-dataservice-server-plugin#382 based on discussion on decoupling steps.
> Revert "[BACKLOG-22188] Decouple constant step from Kettle engine"

- impl/src/main/java/org/pentaho/di/trans/dataservice/clients/AnnotationsQueryService.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/clients/AnnotationsQueryServiceTest.java
Merge Masters: @pentaho-lmartins  and @smmribeiro
Cherry-picks:
* https://github.com/Pentaho/pdi-dataservice-server-plugin/commit/8567644d16bab9da33e6698fba4e8b6fa6acea73
> [SP-5324] Backport of PDI-18214 - If SQL fails in transformations ran on the Pentaho Server, the database connections are not closed. (8.3 Suite)

- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
> [PDI-19396] Do not add null checks to TRUE conditions or regular

- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
@smmribeiro 
@andreramos89 
@renato-s
> [PDI-19396] - Error in Null Handling: Filter Rows, Anything using di.core.Condition

- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
@smmribeiro
@andreramos89
@renato-s
> [SP-6121] - Backport of PDI-19396 - Error in Null Handling: Filter Rows, Anything using di.core.Condition (8.3 Suite)

- impl/pom.xml
- impl/src/main/java/org/pentaho/di/trans/dataservice/clients/AnnotationsQueryService.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/clients/ExecutorQueryService.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/resolvers/MetaStoreResolver.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolver.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceTestController.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/www/RepositoryPublishServlet.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/www/ServletRepositoryProvider.java
- impl/src/main/resources/OSGI-INF/blueprint/services.xml
- impl/src/test/java/org/pentaho/di/trans/dataservice/clients/AnnotationsQueryServiceTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/clients/ExecutorQueryServiceTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/resolvers/TransientResolverTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/serialization/DataServiceFactoryTest.java
- pom.xml
> [BACKLOG-35889] Use kettle plugins for metastore and repository

- assemblies/dataservice/pom.xml
- impl/src/main/resources/OSGI-INF/blueprint/services.xml
> [BACKLOG-35890] Remove dependencies on old metastore and repository

- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceExecutor.java
@smmribeiro 
@andreramos89 
@renato-s
> [SP-6126] - Backport of PDI-19396 - Error in Null Handling: Filter Rows, Anything using di.core.Condition (9.3 Suite)

- pom.xml
This commit is a cherry-pick from master f2b3d7da1
> [SP-6179] [PPP-4654] Get commons-io version from parent pom.

- impl/pom.xml
- impl/src/main/java/org/pentaho/di/trans/dataservice/DataServiceMeta.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/optimization/OptimizationImpactInfo.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/optimization/SourceTargetFields.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/optimization/cache/CachedService.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/optimization/paramgen/ParameterGeneration.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/optimization/pushdown/ParameterPushdown.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/serialization/ServiceTrans.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/serialization/SynchronizationListener.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/streaming/StreamServiceKey.java
- impl/src/main/java/org/pentaho/di/trans/dataservice/ui/DataServiceDelegate.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/optimization/cache/ServiceCacheTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/streaming/StreamServiceKeyTest.java
- pom.xml
[BACKLOG-37825] Guava dependency cleanup
[BACKLOG-37825]: https://hv-eng.atlassian.net/browse/BACKLOG-37825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-37825] Guava dependency cleanup

- assemblies/dataservice-legacy/pom.xml
- assemblies/dataservice/pom.xml
- assemblies/pom.xml
- impl/pom.xml
- pom.xml
[BACKLOG-37681] make test method public[BACKLOG-37681] make test method public
[BACKLOG-37681]: https://hv-eng.atlassian.net/browse/BACKLOG-37681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-37681] - update to new metastore APIs

- impl/src/main/java/org/pentaho/di/trans/dataservice/validation/MongoDbBasicValidation.java
Class may not yet have been loaded
> [PDI-19912] - Error validating transformation in PDI Client Spoon

- assemblies/dataservice-legacy/pom.xml
- assemblies/dataservice-legacy/src/main/feature/feature.xml
- assemblies/dataservice/pom.xml
- assemblies/dataservice/src/main/feature/feature.xml
- pom.xml
dependencies.  Need to suppress those.
> [BACKLOG-40255] Auto-wrapping jars is now pulling in java.*

- impl/src/test/java/org/pentaho/di/trans/dataservice/www/ListDataServicesServletTest.java
- impl/src/test/java/org/pentaho/di/trans/dataservice/www/TransDataServletTest.java
[BACKLOG-43209]-OSGi Assembly Issues
[BACKLOG-43209]: https://hv-eng.atlassian.net/browse/BACKLOG-43209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43209]-OSGi Assembly Issues

- impl/src/test/java/org/pentaho/di/trans/dataservice/ui/controller/DataServiceRemapNoStepsDialogControllerTest.java
[BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version
[BACKLOG-43757]: https://hv-eng.atlassian.net/browse/BACKLOG-43757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version

- impl/src/test/java/org/pentaho/di/trans/dataservice/clients/DataServiceClientTest.java
[BACKLOG-41693]-Fix all the broken testcases in pentaho platform and its plugins
[BACKLOG-41693]: https://hv-eng.atlassian.net/browse/BACKLOG-41693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41693]-Fix all the broken testcases in pentaho platform and its plugins

- assemblies/dataservice-legacy/pom.xml
- assemblies/dataservice/pom.xml
[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
